from . import general
from . import metadata
from . import phone
from . import aadhar
from . import bank_statement
from . import bank
from . import company_details
from . import gst
from . import itr
from . import pan
from . import identification
from . import financial_details
from . import sanctioned_loans
from . import address
from . import additional_company_details
from . import veloce_score
from . import veloce_score_master
from . import finance_offer_detail
from . import v_score_approval_matrix
from . import related_company
from . import business_financial
from . import employment_details
from . import crif_data
from . import level_email