# Generated by Django 3.0.4 on 2021-11-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizcred', '0004_auto_20211115_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='account_type',
            field=models.SmallIntegerField(choices=[('', 'Select'), (1, 'Individual'), (2, 'Institution'), (3, 'Dealer'), (4, 'Lender')], default=1),
        ),
    ]
